apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-index-html
  namespace: homolog
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>devops hml Apache</title></head>
    <body><h1> no que manda devops Devops  Apache rodando no ambiente de homologacao</h1></body>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hml-apache
  namespace: homolog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hml-apache
  template:
    metadata:
      labels:
        app: hml-apache
    spec:
      containers:
        - name: apache
          image: httpd:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/local/apache2/htdocs
      volumes:
        - name: html-volume
          configMap:
            name: apache-index-html

---

apiVersion: v1
kind: Service
metadata:
  name: hml-apache
  namespace: homolog
spec:
  selector:
    app: hml-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hml-apache
  namespace: homolog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-internet
  rules:
    - host: hml-apache.devopslabs.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hml-apache
                port:
                  number: 80
